- hosts: cluster 
  become: yes
  gather_facts: yes

  vars_files:
    - dep7server_vault.yml 

  pre_tasks:
    - name: Disable SWAP since kubernetes can't work with swap enabled
      shell: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: remove swap from fstab
      lineinfile:
        path: '/etc/fstab'
        regexp: '\sswap\s'
        state: 'absent'


  roles:
    - ansible-role-kubernetes

  post_tasks:
    - name: Copy ansible config to $home dir
      copy:
        src:  /etc/kubernetes/admin.conf
        dest: "/home/{{ ansible_user}}/.kube"
        owner: "{{ ansible_user}}"
        group: "{{ ansible_user}}"
      delegate_to: localhost
      when: ansible_hostname == 'cluster01'
    
    - name: Adding the path in the bashrc files  
      lineinfile: 
        dest: "/home/{{ ansible_user}}/.bashrc" 
        line: 'export KUBECONFIG=$HOME/config' 
        insertafter: 'EOF' 
        regexp: 'export KUBECONFIG=$HOME/config' 
        state: present
      delegate_to: localhost
      when: ansible_hostname == 'cluster01'