- hosts: cluster
  become: yes
  gather_facts: yes

  vars_files:
    - dep7server_vault.yml 
  
  pre_tasks:
    - name: check connectivity to hosts (Dummy task)
      shell: echo "{{ hostvars[item]['ansible_host'] }}" 
      with_items:  "{{ groups['cluster'] }}"

      register: cmd_output

    - name: debug ...
      debug: var=cmd_output
      
    # - name: Accept server SSH host keys
    #   connection: local
    #   become: false
    #   shell: |
    #     ssh-keygen -F {{ ansible_host }} ||
    #     ssh-keyscan -H {{ ansible_host }} >> ~/.ssh/known_hosts
    #   register: known_hosts_script
    #   changed_when: "'found' not in known_hosts_script.stdout"

    # - name: Gathering Facts
    #   setup:

    # - name: Add a line to a file if the file does not exist, without passing regexp
    #   lineinfile:
    #     path: /etc/cloud/cloud-init.disabled
    #     line: cloud-init=disabled
    #     create: yes
    #     state: present

#  roles:
#    - set_up_network