ansible_host: 10.42.0.241
ansible_user: cluster04
#ansible_ssh_private_key_file: ~/.ssh/cluster04

# Network configuration
netplan_configuration:
    network:
        version: 2
        ethernets:
            eth0:
                dhcp4: no
                dhcp6: no
                addresses: ["10.42.0.241/24"]
                gateway4: '10.42.0.1'
                nameservers:
                    addresses: ["10.42.0.1", "8.8.8.8"]

docker_users: "{{ ansible_user }}"